services:
  lgtm:
    image: grafana/otel-lgtm
    container_name: otel-lgtm
    ports:
      - "3000:3000" # LGTM UI

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.112.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ${HOST_PROJECT_PATH}/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # health_check extension
      - "4317:40317"   # OTLP gRPC receiver
      - "4318:40318"   # OTLP http receiver
    depends_on:
      - lgtm
